name: animated_native_splash
description: A package which automates the task of creating an animated splash
  screen in a flutter.
version: 1.2.4
homepage: https://github.com/Rexfordasamoah51/flutter_animated_splash_screen
maintainer: Rexford Asamoah

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image: ^3.0.2
  meta: ^1.3.0
  path: ^1.8.0
  xml: ^5.1.0
  yaml: ^3.1.0
  universal_io: ^2.0.4
  

dev_dependencies: 
  flutter_lints: ^1.0.4
